### ISSUE TITLE
What is the difference between Common and Domain?

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [graninas/software-design-in-haskell#9]
Both contain a bunch of types. So what's the difference?
Also there is Types module...

**Comment by graninas** [comment]
Hi @ildar-shaymukhametov , The layout is not always optimal. Common in my projects more often relates to code that can be used in Domain and other places. It's domain-agnostic. Domain is often about specific domain-related or service-related types. What the Types module contains depends on the specific project.

Let me close this issue, I think it is not actual anymore.
